# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-22 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('by', models.CharField(help_text='author', max_length=100, verbose_name='author')),
                ('url', models.CharField(max_length=200)),
                ('score', models.PositiveIntegerField()),
                ('desc', models.TextField()),
                ('sentiment_confidence', models.FloatField()),
                ('sentiment_result', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
